apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghostmomba/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://taiebaminebelhadjali_db_user:*****@cluster0.wczwpwn.mongodb.net/"
