apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   # Garder les données si PVC supprimé
  storageClassName: ""                     # Pas de StorageClass dynamique
  local:
    path: /data/jenkins                    # Dossier sur le node hôte
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - app-worker              # Sur worker-1 ou worker-2
