apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-nfs
  namespace: hrbrain
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteMany    # NFS supporte ReadWriteMany
  storageClassName: ""
  volumeName: jenkins-pv-nfs
  resources:
    requests:
      storage: 10Gi
