apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: hrbrain
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""       # Matcher avec le PV local
  volumeName: jenkins-pv     # Lier explicitement au PV jenkins-pv
  resources:
    requests:
      storage: 10Gi
