apiVersion: v1
kind: Secret
metadata:
  name: hrbrain-secrets
  namespace: hrbrain
type: Opaque
data:
  JWT_SECRET: aHJicmFpbl9zZWNyZXRfa2V5
  MONGO_URI: bW9uZ29kYitzcnY6Ly90YWllYmFtaW5lYmVsaGFkamFsaV9kYl91c2VyOkNvbXBsZXhhdG9tODhAY2x1c3RlcjAud2N6d3B3bi5tb25nb2RiLm5ldC9IUkJyYWluX2Ri
  GOOGLE_CLIENT_ID: REPLACE_WITH_BASE64_GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: REPLACE_WITH_BASE64_GOOGLE_CLIENT_SECRET

---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secrets
  namespace: hrbrain
type: Opaque
data:
  POSTGRES_PASSWORD: c29uYXJxdWJlMTIz
