apiVersion: v1
kind: Secret
metadata:
  name: hrbrain-secrets
  namespace: hrbrain
type: Opaque
# Les valeurs sont encodées en base64
# Pour encoder : echo -n "valeur" | base64
# JWT_SECRET=hrbrain_secret_key → aHJicmFpbl9zZWNyZXRfa2V5
# MONGO_URI → encodé ci-dessous
# GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET → à remplacer par vos vraies valeurs encodées
#   echo -n "ton_client_id" | base64
#   echo -n "ton_client_secret" | base64
data:
  JWT_SECRET: aHJicmFpbl9zZWNyZXRfa2V5
  MONGO_URI: bW9uZ29kYitzcnY6Ly90YWllYmFtaW5lYmVsaGFkamFsaV9kYl91c2VyOkNvbXBsZXhhdG9tODhAY2x1c3RlcjAud2N6d3B3bi5tb25nb2RiLm5ldC9IUkJyYWluX2Ri
  GOOGLE_CLIENT_ID: UEFCU0VfVE9ET19HT09HTEVfQ0xJRU5UX0lE
  GOOGLE_CLIENT_SECRET: UEFCU0VfVE9ET19HT09HTEVfQ0xJRU5UX1NFQ1JFVA==
