---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-data
  namespace: hrbrain
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarqube-pv-data
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-extensions
  namespace: hrbrain
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarqube-pv-extensions
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-logs
  namespace: hrbrain
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarqube-pv-logs
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-postgres
  namespace: hrbrain
  labels:
    app: sonarqube-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarqube-pv-postgres
  resources:
    requests:
      storage: 5Gi
